spring:
  cloud:
    gateway:
      routes:
        - id: users-ws
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws-h2-console
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/h2-console
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /${segment}

        - id: users-ws-login
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

server:
  port: 8082

logging:
  level:
    ROOT: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
