spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8010/eureka

server:
  port: 0

logging:
  level:
    ROOT: DEBUG
